### ISSUE TITLE
the pymongo version should be specified

### ISSUE THREAD

**Issue by littleLi-star7** [Youngestdev/fastapi-mongo#11]
the `mongo_replica_set_client.py` has been removed since pymongo 4.0  and the `motor` module depen it so the version over 4.0 of pymongo cann't work.  In my  test, the version of 3.12.0 can work  `pymongo==3.12.0` the requirements should be update

**Comment by Youngestdev** [comment]
Hi!

thank you for bringing this to my notice! I will be doing a general rewrite soon :)
