### ISSUE TITLE
Functionality duplicate on auth process

### ISSUE THREAD

**Issue by rakovskij-stanislav** [Youngestdev/fastapi-mongo#16]
https://github.com/Youngestdev/fastapi-mongo/blob/master/auth/admin.py#L11

https://github.com/Youngestdev/fastapi-mongo/blob/master/routes/admin.py#L14

As I can see, there are similar code functionality.
`admin.py`'s `validate_login` uses nowhere, this way I cannot find any reason to keep it.

**Comment by Youngestdev** [comment]
Not sure I understand you but one validates login for admin and the other for regular users. @rakovskij-stanislav
