### ISSUE TITLE
权限验证提示{"detail": "Not authenticated" }

### ISSUE THREAD

**Issue by phpsxg** [Youngestdev/fastapi-mongo#9]
def get_authorization_scheme_param(authorization_header_value: str) -> Tuple[str, str]:
    print('sxg')
    if not authorization_header_value:
        return "", ""
    scheme, _, param = authorization_header_value.partition(" ")
    return scheme, param
是因为这个方法得到param 为空

**Comment by Youngestdev** [comment]
Hi, what problem do you have? I'm unable to translate the text.
